### PR TITLE
Beefing up SecretScope

### LINKED ISSUE #99: Applying ACL on non Premium Databricks
If you're running a Databricks instance which is not on the premium tier, ACL is not available.

Regardless if your config has `acls` set or not, the operator will still try to list all ACLs. Listing ACLs will return `Error: {"error_code":"PERMISSION_DENIED","message":"ACL is not supported in your workspace."}` if you are not on the premium tier. 

If ACLs are not available, the config will fail and be put back onto the reconcile loop. It will try create the secret scope again and because it already exists, fail and but put back on the loop.

Instead what should happen is:

* If `acls` is not set in the config, don't call `submitACLs`.
* If `acls` is set in the config and not on premium tier, don't put job back on the reconcile loop and an event should be logged.

### PR DESCRIPTION
**Pull request by JasonTheDeveloper**
This PR resolves #99 and in it I've:

* Check if Secret Scope exists before doing anything. 
* Check for support for ACL in workspace.
* Check if referenced secret in cluster exists.
* If `acls` are not set in config, don't do anything with ACLs.
* General refactoring and bug fixes.

If secret scope exists or ACL is not supported, report event and remove from reconcile loop.
If the referenced secret does not exist, report event and put back on reconcile loop.

### CODE REVIEW

File: controllers/secretscope_controller.go [hunk 1]
```diff
@@ -30,6 +30,7 @@ import (
 
 	databricksv1alpha1 "github.com/microsoft/azure-databricks-operator/api/v1alpha1"
 	dbazure "github.com/xinsnake/databricks-sdk-golang/azure"
+	v1 "k8s.io/api/core/v1"
```
Comment (Azadehkhojandi) [inline controllers/secretscope_controller.go]: please change `v1` to `corev1` for following the same naming convention

File: controllers/secretscope_controller_databricks.go [hunk 2]
```diff
@@ -152,25 +152,66 @@ func (r *SecretScopeReconciler) submitACLs(instance *databricksv1alpha1.SecretSc
...
 }
 
-func (r *SecretScopeReconciler) submit(instance *databricksv1alpha1.SecretScope) error {
+// checkCluster checks if Databricks cluster supports ACLs, and checks if secret scope exists.
+func (r *SecretScopeReconciler) checkCluster(instance *databricksv1alpha1.SecretScope) error {
 	scope := instance.ObjectMeta.Name
 	initialManagePrincipal := instance.Spec.InitialManagePrincipal
 
+	// try create secret scope to see if exists or not.
 	err := r.APIClient.Secrets().CreateSecretScope(scope, initialManagePrincipal)
```
Comment (Azadehkhojandi) [inline controllers/secretscope_controller_databricks.go]: Can we use get instead of creating? or can we use https://docs.azuredatabricks.net/dev-tools/api/latest/secrets.html#get-secret-acl?

File: controllers/secretscope_controller_databricks.go [hunk 3]
```diff
@@ -152,25 +152,66 @@ func (r *SecretScopeReconciler) submitACLs(instance *databricksv1alpha1.SecretSc
...
+func (r *SecretScopeReconciler) checkSecrets(instance *databricksv1alpha1.SecretScope) error {
+	scope := instance.ObjectMeta.Name
+	namespace := instance.Namespace
+
+	// if secret in cluster is reference, see if secret exists.
+	// if secret does not exist, try delete secret scope.
+	for _, secret := range instance.Spec.SecretScopeSecrets {
+		if secret.ValueFrom != nil {
+			if _, err := r.getSecretValueFrom(namespace, secret); err != nil {
+				if er := r.APIClient.Secrets().DeleteSecretScope(scope); er != nil {
```
Comment (Azadehkhojandi) [inline controllers/secretscope_controller_databricks.go]: if we use get secret scope perhaps we don't need to delete the secrete scope here

File: controllers/secretscope_controller_databricks.go [hunk 4]
```diff
@@ -152,25 +152,66 @@ func (r *SecretScopeReconciler) submitACLs(instance *databricksv1alpha1.SecretSc
 	return nil
 }
 
-func (r *SecretScopeReconciler) submit(instance *databricksv1alpha1.SecretScope) error {
+// checkCluster checks if Databricks cluster supports ACLs, and checks if secret scope exists.
+func (r *SecretScopeReconciler) checkCluster(instance *databricksv1alpha1.SecretScope) error {
```
Comment (Azadehkhojandi) [inline controllers/secretscope_controller_databricks.go]: Could you please rename "checkCluster" to "VerifyACL"?
You can create a secret scope without having a cluster and ACL is not related to the cluster. Using the access control list (ACL) is only available with the Azure Databricks Premium Plan.
I don't know much about ACL, we can have a chat with @lace about it and get her opinion.
https://docs.azuredatabricks.net/security/secrets/secret-acl.html

File: controllers/secretscope_controller_databricks.go [hunk 5]
```diff
@@ -152,25 +152,66 @@ func (r *SecretScopeReconciler) submitACLs(instance *databricksv1alpha1.SecretSc
...
 	scope := instance.ObjectMeta.Name
 	initialManagePrincipal := instance.Spec.InitialManagePrincipal
```
Comment (Azadehkhojandi) [inline controllers/secretscope_controller_databricks.go]: InitialManagePrincipal is optional, can we have a null check?
`InitialManagePrincipal string              `json:"initial_manage_permission,omitempty"``

File: controllers/secretscope_controller_databricks.go (hunk 2 above)
Comment (JasonTheDeveloper) [reply controllers/secretscope_controller_databricks.go]: I don't think we can use the _get secret acl_ approach. If the user isn't using a premium tier workspace, the user will get back `Error: {"error_code":"PERMISSION_DENIED","message":"ACL is not supported in your workspace."}`.

However, we could probably list the secret scopes and filter the one we want. That might work.

File: controllers/secretscope_controller_databricks.go (hunk 4 above)
Comment (JasonTheDeveloper) [reply controllers/secretscope_controller_databricks.go]: I've renamed it from `checkCluster` to `verifyWorkspace`. Felt it was more fitting because we're checking the workspace for secrets and ACL support.

File: controllers/secretscope_controller_databricks.go (hunk 2 above)
Comment (JasonTheDeveloper) [reply controllers/secretscope_controller_databricks.go]: Update: Listing the SecretScopes is fine if we're just checking if the SecretScope exists or not but when it comes to checking if ACLs is supported or not, if the SecretScope doesn't exist prior to checking, a `RESOURCE DOES NOT EXIST` is returned rather than a `ACL is not supported in your workspace.` which is what we'd want to see. I've removed ACL checks for now.

File: controllers/secretscope_controller_databricks.go (hunk 3 above)
Comment (JasonTheDeveloper) [reply controllers/secretscope_controller_databricks.go]: The reason for deleting the secret scope is because what happens is if the secret in the cluster doesn't exist, the config will be put back onto the reconcile loop. Next time it runs, it will check if the secret scope exists in databricks and because it was created the previous run, `verifyWorkspace` will cause it to fail and thus wont check again for the secret in cluster. 

Happy for suggestions.

File: controllers/secretscope_controller_databricks.go (hunk 5 above)
Comment (JasonTheDeveloper) [reply controllers/secretscope_controller_databricks.go]: I've created a new issue for this: #125.

File: controllers/secretscope_controller_databricks.go (hunk 2 above)
Comment (JasonTheDeveloper) [reply controllers/secretscope_controller_databricks.go]: I've added back in ACL checks but I've cleaned up the implementation a little.

File: controllers/secretscope_controller_databricks.go (hunk 3 above)
Comment (JasonTheDeveloper) [reply controllers/secretscope_controller_databricks.go]: I've cleaned it up so that it doesn't have to delete the secret scope any longer.

File: controllers/secretscope_controller_databricks.go [hunk 6]
```diff
@@ -150,25 +152,74 @@ func (r *SecretScopeReconciler) submitACLs(instance *databricksv1alpha1.SecretSc
...
+
+	// create the secret scope here otherwise we cannot verify ACL support.
+	err = r.APIClient.Secrets().CreateSecretScope(scope, initialManagePrincipal)
 	if err != nil {
 		return err
 	}
 
-	err = r.submitACLs(instance)
+	// try to list ACLs to see if cluster supports ACL.
+	if instance.Spec.SecretScopeACLs != nil {
```
Comment (Azadehkhojandi) [inline controllers/secretscope_controller_databricks.go]: I was wondering if we can get Databricks SKU by using azure-sdk-for-go when we install operator  - https://github.com/Azure/azure-sdk-for-go/blob/7a9d2769e4a581b0b1bc609c71b59af043e05c98/services/databricks/mgmt/2018-04-01/databricks/models.go

File: controllers/secretscope_controller_test.go [hunk 7]
```diff
@@ -43,11 +46,33 @@ var _ = Describe("SecretScope Controller", func() {
...
 			_ = apiClient.Secrets().DeleteSecretScope(value)
+
+			ss := &databricksv1alpha1.SecretScope{
+				ObjectMeta: metav1.ObjectMeta{
+					Name:      value,
+					Namespace: "default",
+				},
+			}
+
+			_ = k8sClient.Delete(context.Background(), ss)
```
Comment (jakkaj) [inline controllers/secretscope_controller_test.go]: Should this err be checked?

Comment (JasonTheDeveloper) [reply controllers/secretscope_controller_test.go]: I think it should be find.  Both `aclKeyName` and `secretsKeyName`'s names are randomly generated. `_ = k8sClient.Delete(context.Background(), ss)` is just to ensure each `SecretScope` has been fully deleted from the cluster between each unit test.  If for whatever reason `_ = k8sClient.Delete(context.Background(), ss)` fails, the tests will fail anyway.
